databases:
  - name: todocards
    databaseName: todocards
    user: yash1

services:
  - type: web
    name: djangoapi
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn djangoapi.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todocards
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
